### ISSUE TITLE
Large CPU usage increase when using poise meters

### ISSUE THREAD

**Issue by dweetacular** [Nordgaren/Erd-Tools-CPP#2]
When idle with the poise meter features turned on, CPU usage on my machine increases from 29% to 50%. This also causes my CPU temp to jump from 66 degrees to around 87 degrees.

**Comment by Nordgaren** [comment]
[ErdTools.zip](https://github.com/Nordgaren/Erd-Tools-CPP/files/9527477/ErdTools.zip)
can you try with this version of the dll?

**Comment by Nordgaren** [comment]
Also, what CPU do you have, so I can get a range of what works on what hardware?
Right now the bars are on their own threads, each sleeping for 1ms.
I am considering bringing it down to one thread for the two, but I need to see if this works for most people, first, as adding just a 1ms delay causes the bars to flicker, without some additional code.

Thanks! Sorry about that. I never see it on my end, cause I have too many cores. 😆

**Comment by dweetacular** [comment]
Yep, everything is back to normal with this version, thanks! I run on a Ryzen 5 5600x at standard clock speed (3.69 GHz).
