### ISSUE TITLE
Game crashed after start, before intro [Patch 1.08]

### ISSUE THREAD

**Issue by elaeis** [Nordgaren/Erd-Tools-CPP#4]
After patch 1.08 game start (black screen), opened cmd with erd but after 5-15 seconds game process is killed even before intro
Without erd tools (commented dll in config) game starting normally (intro + main menu loaded)

**Comment by Nordgaren** [comment]
I am working on it. I have a bit of work to do before I can get to it, sorry. Will try to get to it tonight or tomorrow!

**Comment by elaeis** [comment]
Now mod works, Thank you very much)
